import type { Metadata } from "next";
import { Inter, Jost } from "next/font/google";
import "./globals.css";

const jost = Jost({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export const metadata: Metadata = {
  title: "xCanvas - AI Mobile Design Agent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${jost.className} ${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
